#  /$$$$$$$   /$$$$$$  /$$   /$$  /$$$$$$  /$$$$$$$$ /$$$$$$$$       /$$      /$$ /$$$$$$$$
# | $$__  $$ /$$__  $$| $$$ | $$ /$$__  $$|__  $$__/| $$_____/      | $$$    /$$$| $$_____/
# | $$  \ $$| $$  \ $$| $$$$| $$| $$  \ $$   | $$   | $$            | $$$$  /$$$$| $$      
# | $$  | $$| $$  | $$| $$ $$ $$| $$$$$$$$   | $$   | $$$$$         | $$ $$/$$ $$| $$$$$   
# | $$  | $$| $$  | $$| $$  $$$$| $$__  $$   | $$   | $$__/         | $$  $$$| $$| $$__/   
# | $$  | $$| $$  | $$| $$\  $$$| $$  | $$   | $$   | $$            | $$\  $ | $$| $$      
# | $$$$$$$/|  $$$$$$/| $$ \  $$| $$  | $$   | $$   | $$$$$$$$      | $$ \/  | $$| $$$$$$$$
# |_______/  \______/ |__/  \__/|__/  |__/   |__/   |________/      |__/     |__/|________/

# ==========================================================
# Donate me Git
# 
# Donate me on my revolut, even 1$ plis plis plis 
# ==========================================================

                                                                                         
                                                                                         
custom: ["https://revolut.me/adrianu8cv"]

