# /$$$$$$$   /$$$$$$  /$$   /$$  /$$$$$$  /$$$$$$$$ /$$$$$$$$       /$$      /$$ /$$$$$$$$
#| $$__  $$ /$$__  $$| $$$ | $$ /$$__  $$|__  $$__/| $$_____/      | $$$    /$$$| $$_____/
#| $$  \ $$| $$  \ $$| $$$$| $$| $$  \ $$   | $$   | $$            | $$$$  /$$$$| $$      
#| $$  | $$| $$  | $$| $$ $$ $$| $$$$$$$$   | $$   | $$$$$         | $$ $$/$$ $$| $$$$$   
#| $$  | $$| $$  | $$| $$  $$$$| $$__  $$   | $$   | $$__/         | $$  $$$| $$| $$__/   
#| $$  | $$| $$  | $$| $$\  $$$| $$  | $$   | $$   | $$            | $$\  $ | $$| $$      
#| $$$$$$$/|  $$$$$$/| $$ \  $$| $$  | $$   | $$   | $$$$$$$$      | $$ \/  | $$| $$$$$$$$
#|_______/  \______/ |__/  \__/|__/  |__/   |__/   |________/      |__/     |__/|________/
                                                                                         
                                                                                         
                                                                                         
custom: ["https://revolut.me/adrianu8cv"]

# Pay me now
# GIMMEE YOUR MONEY 
# NOW

